#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# PiVision — Raspberry Pi 4 installer
# Installs all dependencies needed to run camera.py
#
# Usage:
#   chmod +x install.sh
#   ./install.sh
#
# Tested on: Raspberry Pi OS Bookworm (12) and Bullseye (11), 64-bit
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

VENV_DIR="$HOME/pivision-env"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[PiVision]${NC} $*"; }
warn()    { echo -e "${YELLOW}[PiVision]${NC} $*"; }
error()   { echo -e "${RED}[PiVision]${NC} $*" >&2; }

# ── 1. System packages ────────────────────────────────────────────────────────
info "Updating package lists…"
sudo apt-get update -qq

info "Installing system dependencies…"
sudo apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev \
    libopencv-dev \
    python3-opencv \
    libatlas-base-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libv4l-dev \
    v4l-utils \
    libhdf5-dev \
    libhdf5-serial-dev \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    gcc \
    g++ \
    make \
    curl \
    git

# ── 2. Python virtual environment ─────────────────────────────────────────────
# Raspberry Pi OS Bookworm (Python 3.11+) enforces PEP 668 — pip installs
# must go into a venv, not the system Python.
info "Creating Python virtual environment at $VENV_DIR …"
python3 -m venv "$VENV_DIR" --system-site-packages

# Activate for the rest of this script
# shellcheck source=/dev/null
source "$VENV_DIR/bin/activate"

info "Upgrading pip inside venv…"
pip install --upgrade pip --quiet

# ── 3. Python packages ─────────────────────────────────────────────────────────
info "Installing Python packages…"

# opencv-python-headless — no GUI deps needed on a headless Pi
# If python3-opencv (from apt) is already present via --system-site-packages,
# this is a no-op, which is fine.
pip install \
    opencv-python-headless \
    firebase-admin \
    openai \
    --quiet

info "Python packages installed ✓"

# ── 4. Verify camera is accessible ────────────────────────────────────────────
info "Checking for USB camera devices…"
if v4l2-ctl --list-devices 2>/dev/null | grep -q "video"; then
    info "Camera device(s) found:"
    v4l2-ctl --list-devices 2>/dev/null | grep -A1 "video" | sed 's/^/    /'
else
    warn "No camera detected right now. Plug in your USB webcam and try:"
    warn "  v4l2-ctl --list-devices"
fi

# ── 5. Create the activation wrapper script ────────────────────────────────────
RUNNER="$SCRIPT_DIR/run.sh"
cat > "$RUNNER" <<RUNSCRIPT
#!/usr/bin/env bash
# Auto-generated by install.sh — activates the venv and runs camera.py
set -euo pipefail
source "$VENV_DIR/bin/activate"
exec python3 "$SCRIPT_DIR/camera.py" "\$@"
RUNSCRIPT
chmod +x "$RUNNER"
info "Created runner script: $RUNNER"

# ── 6. Create a systemd service (optional) ─────────────────────────────────────
SERVICE_FILE="/etc/systemd/system/pivision.service"

cat > /tmp/pivision.service <<SERVICE
[Unit]
Description=PiVision Camera — Motion Detection + Firebase
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$SCRIPT_DIR
ExecStart=$RUNNER
Restart=on-failure
RestartSec=5
# Set your OpenAI key here (or use an EnvironmentFile= instead)
Environment=OPENAI_API_KEY=REPLACE_WITH_YOUR_KEY
Environment=CAMERA_INDEX=0
Environment=MOTION_THRESHOLD=3000
Environment=ANALYSIS_INTERVAL=60

[Install]
WantedBy=multi-user.target
SERVICE

if sudo cp /tmp/pivision.service "$SERVICE_FILE" 2>/dev/null; then
    sudo systemctl daemon-reload
    info "systemd service installed at $SERVICE_FILE"
    info "  → Edit $SERVICE_FILE to add your OPENAI_API_KEY"
    info "  → Then run:"
    info "      sudo systemctl enable pivision   # start on boot"
    info "      sudo systemctl start  pivision   # start now"
    info "      sudo journalctl -u pivision -f   # view logs"
else
    warn "Could not install systemd service (permission denied). You can do it manually:"
    warn "  sudo cp /tmp/pivision.service $SERVICE_FILE"
    warn "  sudo systemctl daemon-reload && sudo systemctl enable pivision"
fi

# ── 7. Print final instructions ───────────────────────────────────────────────
echo ""
echo "────────────────────────────────────────────────────────────"
echo -e "${GREEN}  PiVision install complete!${NC}"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Add your Firebase service account file:"
echo "       pi/serviceAccount.json"
echo "     Generate it at:"
echo "       https://console.firebase.google.com/project/pivision-28ddb/settings/serviceaccounts"
echo "     → 'Generate new private key' → save as pi/serviceAccount.json"
echo ""
echo "  2. Set your OpenAI API key:"
echo "       export OPENAI_API_KEY='sk-...'"
echo ""
echo "  3. Run the camera script:"
echo "       ./run.sh"
echo ""
echo "  Or run directly:"
echo "       source $VENV_DIR/bin/activate"
echo "       python3 camera.py"
echo "────────────────────────────────────────────────────────────"
